### ISSUE TITLE
Setup React Native on Windows

### ISSUE THREAD

**Issue by nextfunc** [nextfunc/training-react-native#1]
1. Open this link:  https://facebook.github.io/react-native/docs/getting-started.html

![screenshot at apr 13 22-00-38](https://user-images.githubusercontent.com/38009703/38742213-25736b12-3f66-11e8-8972-02da9c260f6d.png)

2. Click on "Building Project With Native Code"
3. Select "Windows" and "Android"
4. Follow the tutorial to setup React native on your PC

**Comment by ATtung** [comment]
Done

**Comment by liugondar** [comment]
Done

**Comment by nhuttanmt** [comment]
Done
